"""
agents/ci_generator.py — GitHub Actions CI Workflow Generator.

Generates a ready-to-use .github/workflows/pr-guard.yml file that runs
PR Guard automatically on every pull request in the target repository.

No LLM call — pure string templating. Fast and free.
"""

_WORKFLOW_TEMPLATE = """\
# PR Guard — Automated PR Audit
# Generated by PR Guard (https://github.com/Justvictorya/PR-Guard)
#
# SETUP: Add these secrets to your repo at
#   Settings → Secrets and variables → Actions → New repository secret
#
#   GROQ_API_KEY   — from https://console.groq.com
#   PR_GUARD_TOKEN — GitHub personal access token (public_repo scope)
#                    from https://github.com/settings/tokens

name: PR Guard Audit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-guard:
    name: Run PR Guard Audit
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write   # needed to post the report as a PR comment

    steps:
      - name: Checkout PR Guard
        uses: actions/checkout@v4
        with:
          repository: Justvictorya/PR-Guard
          path: pr-guard-tool

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r pr-guard-tool/requirements.txt

      - name: Run PR Guard
        id: audit
        env:
          GITHUB_TOKEN: ${{ secrets.PR_GUARD_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          LLM_PROVIDER: groq
          LLM_MODEL: openai/gpt-oss-120b
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          cd pr-guard-tool
          python3 - <<'PYTHON'
          import os, sys
          from dotenv import load_dotenv
          load_dotenv()
          sys.path.insert(0, ".")
          from github_client import fetch_data
          from agents.policy_parser import parse_policy
          from agents.diff_auditor import audit_diff
          from agents.api_extractor import extract_apis
          from agents.similar_repos import find_similar
          from agents.reporter import generate_report
          from concurrent.futures import ThreadPoolExecutor, as_completed

          url = os.environ["PR_URL"]
          pr_data = fetch_data(url)
          repo = pr_data["repo_obj"]

          with ThreadPoolExecutor(max_workers=3) as ex:
              fp = ex.submit(parse_policy, repo)
              fa = ex.submit(extract_apis, pr_data)
              for f in as_completed([fp, fa]):
                  if f is fp:
                      checklist = f.result()
                      fd = ex.submit(audit_diff, pr_data, checklist)
                  else:
                      api_entries = f.result()
              findings = fd.result()

          similar = find_similar(repo)
          report  = generate_report(pr_data, checklist, findings, api_entries, similar)
          with open("/tmp/pr-guard-report.md", "w") as out:
              out.write(report)
          print(report[:500])
          PYTHON

      - name: Post report as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: /tmp/pr-guard-report.md
          header: pr-guard
"""


def generate_workflow(repo_full_name: str = "") -> str:
    """Return the GitHub Actions workflow YAML as a string.

    Args:
        repo_full_name : optional "owner/repo" — used only for the header comment.

    Returns:
        Ready-to-use YAML string for .github/workflows/pr-guard.yml
    """
    yaml = _WORKFLOW_TEMPLATE
    if repo_full_name:
        yaml = yaml.replace(
            "# Generated by PR Guard",
            f"# Generated for {repo_full_name} by PR Guard",
        )
    return yaml


def get_setup_instructions() -> str:
    """Return plain-English setup instructions shown in the Streamlit UI."""
    return """\
### How to install PR Guard CI in your repository

1. **Add two secrets** to your target repo:
   - Go to `Settings → Secrets and variables → Actions → New repository secret`
   - Add `GROQ_API_KEY` (from [console.groq.com](https://console.groq.com))
   - Add `PR_GUARD_TOKEN` (GitHub token with `public_repo` scope from [github.com/settings/tokens](https://github.com/settings/tokens))

2. **Create the workflow file** in your repo:
   - Create `.github/workflows/pr-guard.yml`
   - Paste the generated YAML below

3. **Commit and push** — PR Guard will now run automatically on every new pull request
   and post the audit report as a PR comment.
"""


# ---------------------------------------------------------------------------
# Smoke-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    yaml = generate_workflow("acme/my-app")
    print(yaml[:500])
    assert "pr-guard" in yaml
    assert "GROQ_API_KEY" in yaml
    assert "pull_request" in yaml
    print("\nagents/ci_generator.py OK ✓")
